name: faabul_color_picker
description: A simple color picker with focus on good UX. Work with Material colors and parses custom colors in hex format.
version: 1.1.0
homepage: https://github.com/yomio/faabul_color_picker
repository: https://github.com/yomio/faabul_color_picker.git
issue_tracker: https://github.com/yomio/faabul_color_picker/issues
topics:
 - ui
 - picker
 - color
 - widgets
 - widget
screenshots:
  - description: 'UI of the color picker dialog'
    path: doc/sample.png

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  faabul_color_conversion: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
